server:
  error:
    include-stacktrace : never
  port: 8081

spring:
  datasource:
    driver-class-name : com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testDB?allowPublicKeyRetrieval=true&useSSL=false
    username : root
    password : Tognazzi1!
    platform : org.hibernate.dialect.MySQL5InnoDBDialect
  jpa:
    show_sql : true
    generate-ddl : true
    hibernate:
      ddl-auto : none
