server:
  port: 8082

spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    platform: org.hibernate.dialect.H2Dialect
  jpa:
    show_sql : true
    generate-ddl : true
    hibernate:
      ddl-auto : create
  mail:
    username: fiorellarossi666@gmail.com
    password: Fiorellarossi1
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  secret: chiavesupersegretissima
  prefix: 'Bearer '
  param: Authorization

logging:
  level:
    org.springframework.cache: TRACE